module.exports = {
    '@context':        'fua.load.rdf',
    'dct:identifier':  __filename,
    'dct:format':      'application/fua.load+js',
    'dct:title':       'load',
    'dct:alternative': '@fua/resource.ontology.science/qudt',
    'dct:requires':    [{
        'dct:identifier': '../../data/qudt/schema/qudt.ttl',
        'dct:format':     'text/turtle'
    }, {
        'dct:identifier': '../../data/qudt/schema/datatype.ttl',
        'dct:format':     'text/turtle'
    }, {
        'dct:identifier': '../../data/qudt/schema/mathematics.ttl',
        'dct:format':     'text/turtle'
    }, {
        'dct:identifier': '../../data/qudt/vocab/constant.ttl',
        'dct:format':     'text/turtle'
    }, {
        'dct:identifier': '../../data/qudt/vocab/discipline.ttl',
        'dct:format':     'text/turtle'
    }, {
        'dct:identifier': '../../data/qudt/vocab/prefix.ttl',
        'dct:format':     'text/turtle'
    }, {
        'dct:identifier': '../../data/qudt/vocab/dimensionvector.ttl',
        'dct:format':     'text/turtle'
    }, {
        'dct:identifier': '../../data/qudt/vocab/quantitykind.ttl',
        'dct:format':     'text/turtle'
    }, {
        'dct:identifier': '../../data/qudt/vocab/soqk.ttl',
        'dct:format':     'text/turtle'
    }, {
        'dct:identifier': '../../data/qudt/vocab/sou.ttl',
        'dct:format':     'text/turtle'
    }, {
        'dct:identifier': '../../data/qudt/vocab/unit.ttl',
        'dct:format':     'text/turtle'
    }]
};
